version: '3'

services:
  express-proxy:
    build: ./server/gateway # Path to proxy server Dockerfile
    ports:
      - "5000:5000" # port 5000
    depends_on:
      - payment-service # Ensure the pay service container is started first
      - course-management-service
      - notification-service
      - learner-service
      - user-service

  payment-service:
    build: ./server/payment-service # Path to pay service Dockerfile
    ports:
      - "5002:5002" # port 5002

  course-management-service:
    build: ./server/course-management-service 
    ports:
      - "5001:5001" # port 5001

  notification-service:
    build: ./server/Notification-service 
    ports:
      - "5003:5003" # port 5003

  learner-service:
    build: ./server/learner-service 
    ports:
      - "5005:5005" # port 5005

  user-service:
    build: ./server/user-service 
    ports:
      - "5004:5004" # port 5004
